---
# This playbook deploys all sub playbooks

- name: configure heavy forwarder
  hosts: heavy_forwarders
  user: root
  vars:
    # splunk binary to install
    splunk_binary: 'splunk-6.2.0-237341-Linux-x86_64.tgz'

  roles:
    - common
    - heavy_forwarder
